# Adapted from sample vite workflow file: https://vitejs.dev/guide/static-deploy#github-pages
name: deploy

on:
  release:
    types: [published]
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    # See docs: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      # TODO: Update/uncomment once we have deploy the app to replace the legacy tool
      # - name: Add prod scripts
      #   run: |
      #     add_script='<script async src="https://w.appzi.io/w.js?token=YVTHd"></script><script defer data-domain="annotate.neurobagel.org" src="https://plausible.neurobagel.org/js/script.js"></script>'
      #     # Need to use single quotes around sed to avoid ! to be interpreted as a history expansion character
      #     sed -i 's|<!-- REPLACE_ME_NB_ANNOTATE_HEADER_SCRIPT_REPLACE_ME -->|'"${add_script}"'|' index.html

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
